version: '3.8'

# TODO : ./www/assets as a volume

services:
  www:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # - ./www/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/usr/share/nginx/html 
      # TODO : ./www/assets as a volume
    networks: [athens-ar]

  www_admin:
    image: node:latest
    command: npx http-server -p 3000 /usr/src/app/public
    volumes:
      - ./www/assets:/usr/src/app/assets # TODO : ./www/assets as a volume
      - ./www_admin/public:/usr/src/app/public
    ports:
      - "8082:3000"
    depends_on:
      - db_postgis
    networks: [athens-ar]

  api_go:
    build:
      context: ./api_go
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      POSTGRES_DB: ${DB_POSTGIS_DB}
      POSTGRES_USER: ${DB_POSTGIS_USER}
      POSTGRES_PASSWORD: ${DB_POSTGIS_USER}
    depends_on:
      - db_postgis
    networks: [athens-ar]

  db_postgis:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_POSTGIS_DB}
      POSTGRES_USER: ${DB_POSTGIS_USER}
      POSTGRES_PASSWORD: ${DB_POSTGIS_USER}
    volumes:
      - ./db_postgis/init:/docker-entrypoint-initdb.d
      - db_postgis-volume:/var/lib/postgresql/data
    networks: [athens-ar]

networks: 
  athens-ar:
    driver: bridge

volumes:
  db_postgis-volume: